version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "8080:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - internal

  service_api:
    build:
      context: .
      dockerfile: docker/Dockerfile.service_api
    image: "${IMAGE_BASE}service_api${BUILD_NUMBER}"
    ports:
      - "80"
    environment:
      - "VIRTUAL_HOST=service_api"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - internal

networks:
  internal:
