FROM debian:stretch

RUN apt-get update && apt-get install --no-install-recommends -y \
    python3 \
    python3-pip

RUN pip3 install --upgrade pip==19.1.1
RUN pip3 install setuptools==40.0

RUN mkdir /package

COPY . /package

WORKDIR /package

RUN pip3 install -r requirements.txt

ENTRYPOINT ["python3", "launch.py"]
